name: 'Frontend React Build Artefato'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs: 
  - job: BuildAndTest
    displayName: 'Publicação do Artefato de React Front'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.0x'
        displayName: 'Install Node.js'

      - task: CmdLine@2
        inputs:
          script:
            'npm install -g firebase-tools' 
            'npm install'
            'npm run build'
        displayName: 'npm install firebase and build'

      -task: CopyFiles@2
        inputs:
          script:
            firebase deploy --token $(FIREBASE_TOKEN)
        displayName: 'Inclusão do token do firebase'

      env:
        FIREBASE_TOKEN: $(FIREBASE_TOKEN)


      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/build'
          artifact: 'react-EventPlan'
          publishLocation: 'pipeline-prod'